[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solhot = "7hgP3DN1LsuaoHJEJ81iwqcHA6e4tsN2QdS5JFYdDUkn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/m1air/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
